from glob import glob
from setuptools import find_packages, setup

package_name = "parking_robot_bringup"

setup(
    name=package_name,
    version="0.1.0",
    packages=find_packages(exclude=["test"]),
    data_files=[
        ("share/ament_index/resource_index/packages", ["resource/" + package_name]),
        ("share/" + package_name, ["package.xml", "README.md"]),
        ("share/" + package_name + "/launch", glob("launch/*.launch.py")),
        ("share/" + package_name + "/config", glob("config/*.yaml")),
        ("share/" + package_name + "/behavior_trees", glob("behavior_trees/*.xml")),
        ("share/" + package_name + "/maps", glob("maps/*")),
    ],
    install_requires=["setuptools"],
    zip_safe=True,
    maintainer="dog",
    maintainer_email="dog@example.invalid",
    description="Isolated Phase 2 Core Simple Nav2 baseline with fake base.",
    license="Proprietary",
    tests_require=["pytest"],
    entry_points={
        "console_scripts": [
            "phase2_fake_base = parking_robot_bringup.phase2_fake_base:main",
            "phase4_vehicle_cmd_fake_base = parking_robot_bringup.phase4_vehicle_cmd_fake_base:main",
            "phase2_goal_test_runner = parking_robot_bringup.phase2_goal_test_runner:main",
            "phase2_sequence_cancel_test_runner = parking_robot_bringup.phase2_sequence_cancel_test_runner:main",
            "phase2_failure_test_runner = parking_robot_bringup.phase2_failure_test_runner:main",
            "phase4_p4b_preflight_monitor = parking_robot_bringup.phase4_p4b_preflight_monitor:main",
            "phase4_p4b_nav2_scenario_runner = parking_robot_bringup.phase4_p4b_nav2_scenario_runner:main",
            "phase4_p4b_raw_twist_fixture = parking_robot_bringup.phase4_p4b_raw_twist_fixture:main",
            "phase4_p4b_synthetic_obstacles = parking_robot_bringup.phase4_p4b_synthetic_obstacles:main",
            "phase4_p4e1b_clear_runner = parking_robot_bringup.phase4_p4e1b_clear_runner:main",
            "phase4_p4e2a_slowdown_runner = parking_robot_bringup.phase4_p4e2a_slowdown_runner:main",
            "phase4_p4e2b_temporary_stop_runner = parking_robot_bringup.phase4_p4e2b_temporary_stop_runner:main",
            "phase4_p4e3a_mission_cancel_runner = parking_robot_bringup.phase4_p4e3a_mission_cancel_runner:main",
            "phase4_p4e3b_stopped_cancel_runner = parking_robot_bringup.phase4_p4e3b_stopped_cancel_runner:main",
            "phase4_p4e5b_temporary_block_runner = parking_robot_bringup.phase4_p4e5b_temporary_block_runner:main",
            "phase4_p4e6a_persistent_block_runner = parking_robot_bringup.phase4_p4e6a_persistent_block_runner:main",
            "phase4_p4e6a7_clear_domain_runner = parking_robot_bringup.phase4_p4e6a7_clear_domain_runner:main",
            "phase4_p4e6b_health_failure_runner = parking_robot_bringup.phase4_p4e6b_health_failure_runner:main",
            "phase4_p4e6b2a2a_init_seam = parking_robot_bringup.phase4_p4e6b2a2a_init_seam:main",
            "phase4_p4e6b_observation_relay = parking_robot_bringup.phase4_p4e6b_observation_relay:main",
            "phase4_p4e6b_tf_observation_relay = parking_robot_bringup.phase4_p4e6b_tf_observation_relay:main",
            "phase4_p4e6b_feedback_relay = parking_robot_bringup.phase4_p4e6b_feedback_relay:main",
            "phase4_p4e6c_recovery_feedback_relay = parking_robot_bringup.phase4_p4e6c_recovery_feedback_relay:main",
            "phase4_p4e6c_progress_observer = parking_robot_bringup.phase4_p4e6c_progress_observer:main",
            "phase4_p4e6c_live_driver = parking_robot_bringup.phase4_p4e6c_live_driver:main",
            "phase4_p4e6b_collision_reason_observer = parking_robot_bringup.phase4_p4e6b_collision_reason_observer:main",
            "r3h_instance_guard = parking_robot_bringup.r3h_instance_guard:main",
        ],
    },
)
