tmini_collision_self_mask:
  ros__parameters:
    input_topic: /r23_r5/scan
    output_topic: /r23_r5/scan_experimental
    expected_frame: laser_frame
    footprint_x_min: -0.145
    footprint_x_max: 0.755
    footprint_y_min: -0.300
    footprint_y_max: 0.300
    sensor_x: 0.703
    sensor_y: 0.0
    sensor_yaw: 0.0
